steps:
  # 1단계: Dockerfile을 사용해 컨테이너 이미지를 빌드합니다.
  # $PROJECT_ID, ${COMMIT_SHA} 등은 Cloud Build가 자동으로 채워주는 변수입니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/prmart/studio:${COMMIT_SHA}', '.', '-f', 'Dockerfile']

  # 2단계: 빌드된 이미지를 Artifact Registry(구글 컨테이너 레지스트리)에 푸시합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/prmart/studio:${COMMIT_SHA}']

  # 3단계: 새로운 이미지로 Cloud Run 서비스를 업데이트(배포)합니다.
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'studio' # Cloud Run 서비스 이름 (로그에 명시된 'studio')
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/prmart/studio:${COMMIT_SHA}'
      - '--region=us-central1'
      - '--quiet'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/prmart/studio:${COMMIT_SHA}'
